### ISSUE TITLE
Distribution-to-Histogram conversion yields invalid data

### ISSUE THREAD

**Issue by cboggs** [prometheus-community/stackdriver_exporter#25] opened 2018-04-12 15:11 UTC
### Setup
Run stackdriver_exporter with `--monitoring.metrics-type-prefixes=bigtable.googleapis.com`.

### Expected
Metrics like `stackdriver_bigtable_table_bigtable_googleapis_com_server_latencies_count` should present as monotonically increasing counters, as would normal Prometheus histogram counters.

### Actual
Metrics `stackdriver_bigtable_table_bigtable_googleapis_com_server_latencies_count` frequently decrement and oscillate in ways they shouldn't.

Screenshot:
![screen shot 2018-04-12 at 9 10 57 am](https://user-images.githubusercontent.com/3492944/38686410-74085250-3e31-11e8-8e2c-a29878b00b80.png)

This inherently throws off quantile calculations on the respective histogram buckets, as the individual bucket counts oscillate in the same manner. This yields per-bucket rates that provide errant quantiles (ex: 47-day-long latency measurements on p50).

**Comment by nilebox** [comment] 2021-07-29 06:29
It's not just `_count`, but bucket values as well.
The problem is due to `DISTRIBUTION` + `DELTA` metrics in Cloud Monitoring (Stackdriver) returning deltas for a given interval, whereas Prometheus counter should present the total accumulated count.

Related: https://github.com/prometheus-community/stackdriver_exporter/issues/116#issuecomment-888839293

**Comment by kgeckhart** [comment] 2023-05-26 19:08
@SuperQ I think this one can be closed now that #168 is merged

**Closed** 2023-05-27 08:08 UTC
